import json
import re

from runtime.tools.tool_manager import ToolManager


class ToolCaller:
    """
    Executes tool requests generated by AI agents.
    Automatically cleans Markdown code fences.
    """

    def __init__(self):
        self.tools = ToolManager()

    def execute(self, tool_request: dict):

        tool = tool_request["tool"]
        action = tool_request["action"]
        args = tool_request.get("args", {})

        print(f"\nTool : {tool}")
        print(f"Action : {action}")

        return self.tools.execute(tool, action, **args)

    def clean_json(self, text: str):

        text = text.strip()

        # Remove ```json
        text = re.sub(r"^```json", "", text, flags=re.IGNORECASE)

        # Remove ```
        text = re.sub(r"^```", "", text)

        text = re.sub(r"```$", "", text)

        return text.strip()

    def execute_json(self, response: str):

        cleaned = self.clean_json(response)

        print("\nCleaned JSON:\n")
        print(cleaned)

        data = json.loads(cleaned)

        return self.execute(data)